//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunchernoNakuKoroniJa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaunchernoNakuKoroniJa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Game couldn&apos;t be found at the existing path.
        ///
        ///Please check if the path is correct in
        ///Launcher no Naku Koro ni (Ja).exe.config..
        /// </summary>
        public static string CantFindGame {
            get {
                return ResourceManager.GetString("CantFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game path incorrect.
        /// </summary>
        public static string CantFindGameTitle {
            get {
                return ResourceManager.GetString("CantFindGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t find game&apos;s path in
        ///Launcher no Naku Koro ni (Ja).exe.config!
        ///
        ///Please make sure it is properly defined..
        /// </summary>
        public static string CantFindPath {
            get {
                return ResourceManager.GetString("CantFindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not in app settings.
        /// </summary>
        public static string CantFindPathTitle {
            get {
                return ResourceManager.GetString("CantFindPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 1.
        /// </summary>
        public static string Cic1TB1 {
            get {
                return ResourceManager.GetString("Cic1TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~代わりのいる君たちへ~.
        /// </summary>
        public static string Cic1TB2 {
            get {
                return ResourceManager.GetString("Cic1TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 2.
        /// </summary>
        public static string Cic2TB1 {
            get {
                return ResourceManager.GetString("Cic2TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~近日公開~.
        /// </summary>
        public static string Cic2TB2 {
            get {
                return ResourceManager.GetString("Cic2TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 3.
        /// </summary>
        public static string Cic3TB1 {
            get {
                return ResourceManager.GetString("Cic3TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~近日公開~.
        /// </summary>
        public static string Cic3TB2 {
            get {
                return ResourceManager.GetString("Cic3TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 4.
        /// </summary>
        public static string Cic4TB1 {
            get {
                return ResourceManager.GetString("Cic4TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~近日公開~.
        /// </summary>
        public static string Cic4TB2 {
            get {
                return ResourceManager.GetString("Cic4TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第5章.
        /// </summary>
        public static string HigA1TB1 {
            get {
                return ResourceManager.GetString("HigA1TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目明し編.
        /// </summary>
        public static string HigA1TB2 {
            get {
                return ResourceManager.GetString("HigA1TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第6章.
        /// </summary>
        public static string HigA2TB1 {
            get {
                return ResourceManager.GetString("HigA2TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 罪滅し編.
        /// </summary>
        public static string HigA2TB2 {
            get {
                return ResourceManager.GetString("HigA2TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第7章.
        /// </summary>
        public static string HigA3TB1 {
            get {
                return ResourceManager.GetString("HigA3TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 皆殺し編.
        /// </summary>
        public static string HigA3TB2 {
            get {
                return ResourceManager.GetString("HigA3TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第8章.
        /// </summary>
        public static string HigA4TB1 {
            get {
                return ResourceManager.GetString("HigA4TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 祭囃し編.
        /// </summary>
        public static string HigA4TB2 {
            get {
                return ResourceManager.GetString("HigA4TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンソール.
        /// </summary>
        public static string HigConTB1 {
            get {
                return ResourceManager.GetString("HigConTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アーク.
        /// </summary>
        public static string HigConTB2 {
            get {
                return ResourceManager.GetString("HigConTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第10章.
        /// </summary>
        public static string HigHouTB1 {
            get {
                return ResourceManager.GetString("HigHouTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひぐらしのなく頃に奉.
        /// </summary>
        public static string HigHouTB2 {
            get {
                return ResourceManager.GetString("HigHouTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第1章.
        /// </summary>
        public static string HigQ1TB1 {
            get {
                return ResourceManager.GetString("HigQ1TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鬼隠し編.
        /// </summary>
        public static string HigQ1TB2 {
            get {
                return ResourceManager.GetString("HigQ1TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第2章.
        /// </summary>
        public static string HigQ2TB1 {
            get {
                return ResourceManager.GetString("HigQ2TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 綿流し編.
        /// </summary>
        public static string HigQ2TB2 {
            get {
                return ResourceManager.GetString("HigQ2TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第3章.
        /// </summary>
        public static string HigQ3TB1 {
            get {
                return ResourceManager.GetString("HigQ3TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 祟殺し編.
        /// </summary>
        public static string HigQ3TB2 {
            get {
                return ResourceManager.GetString("HigQ3TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第4章.
        /// </summary>
        public static string HigQ4TB1 {
            get {
                return ResourceManager.GetString("HigQ4TB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暇潰し編.
        /// </summary>
        public static string HigQ4TB2 {
            get {
                return ResourceManager.GetString("HigQ4TB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第9章.
        /// </summary>
        public static string HigReiTB1 {
            get {
                return ResourceManager.GetString("HigReiTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ひぐらしのなく頃に礼.
        /// </summary>
        public static string HigReiTB2 {
            get {
                return ResourceManager.GetString("HigReiTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランチャーのなく頃に.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to うみねこのなく頃に咲.
        /// </summary>
        public static string Umi07TTB1 {
            get {
                return ResourceManager.GetString("Umi07TTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オマケシナリオ『07th_theater』.
        /// </summary>
        public static string Umi07TTB2 {
            get {
                return ResourceManager.GetString("Umi07TTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第2章.
        /// </summary>
        public static string UmiCTB1 {
            get {
                return ResourceManager.GetString("UmiCTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to うみねこのなく頃に散.
        /// </summary>
        public static string UmiCTB2 {
            get {
                return ResourceManager.GetString("UmiCTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第4章.
        /// </summary>
        public static string UmiHTB1 {
            get {
                return ResourceManager.GetString("UmiHTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to うみねこのなく頃に羽.
        /// </summary>
        public static string UmiHTB2 {
            get {
                return ResourceManager.GetString("UmiHTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第1章.
        /// </summary>
        public static string UmiQTB1 {
            get {
                return ResourceManager.GetString("UmiQTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to うみねこのなく頃に.
        /// </summary>
        public static string UmiQTB2 {
            get {
                return ResourceManager.GetString("UmiQTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第5章.
        /// </summary>
        public static string UmiSTB1 {
            get {
                return ResourceManager.GetString("UmiSTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to うみねこのなく頃に咲.
        /// </summary>
        public static string UmiSTB2 {
            get {
                return ResourceManager.GetString("UmiSTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第3章.
        /// </summary>
        public static string UmiTTB1 {
            get {
                return ResourceManager.GetString("UmiTTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to うみねこのなく頃に翼.
        /// </summary>
        public static string UmiTTB2 {
            get {
                return ResourceManager.GetString("UmiTTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t start game due to unknown error..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start game.
        /// </summary>
        public static string UnknownErrorTitle {
            get {
                return ResourceManager.GetString("UnknownErrorTitle", resourceCulture);
            }
        }
    }
}
