//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunchernoNakuKoroni.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaunchernoNakuKoroni.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciconia1\ciconia_phase1.exe.
        /// </summary>
        public static string Cic1_exe {
            get {
                return ResourceManager.GetString("Cic1_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\notepad.exe.
        /// </summary>
        public static string Cic2_exe {
            get {
                return ResourceManager.GetString("Cic2_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\notepad.exe.
        /// </summary>
        public static string Cic3_exe {
            get {
                return ResourceManager.GetString("Cic3_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\notepad.exe.
        /// </summary>
        public static string Cic4_exe {
            get {
                return ResourceManager.GetString("Cic4_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higurashi5to8\HigurashiEp05.exe.
        /// </summary>
        public static string HigA1_exe {
            get {
                return ResourceManager.GetString("HigA1_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higurashi5to8\HigurashiEp06.exe.
        /// </summary>
        public static string HigA2_exe {
            get {
                return ResourceManager.GetString("HigA2_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higurashi5to8\HigurashiEp07.exe.
        /// </summary>
        public static string HigA3_exe {
            get {
                return ResourceManager.GetString("HigA3_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higurashi5to8\HigurashiEp08.exe.
        /// </summary>
        public static string HigA4_exe {
            get {
                return ResourceManager.GetString("HigA4_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\notepad.exe.
        /// </summary>
        public static string HigCon_exe {
            get {
                return ResourceManager.GetString("HigCon_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\notepad.exe.
        /// </summary>
        public static string HigHou_exe {
            get {
                return ResourceManager.GetString("HigHou_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higurashi1to4\HigurashiEp01.exe.
        /// </summary>
        public static string HigQ1_exe {
            get {
                return ResourceManager.GetString("HigQ1_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higurashi1to4\HigurashiEp02.exe.
        /// </summary>
        public static string HigQ2_exe {
            get {
                return ResourceManager.GetString("HigQ2_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higurashi1to4\HigurashiEp03.exe.
        /// </summary>
        public static string HigQ3_exe {
            get {
                return ResourceManager.GetString("HigQ3_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higurashi1to4\HigurashiEp04.exe.
        /// </summary>
        public static string HigQ4_exe {
            get {
                return ResourceManager.GetString("HigQ4_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HigurashiRei\onscripter-en.exe.
        /// </summary>
        public static string HigRei_exe {
            get {
                return ResourceManager.GetString("HigRei_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\notepad.exe.
        /// </summary>
        public static string Umi07T_exe {
            get {
                return ResourceManager.GetString("Umi07T_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umineko5to8\Umineko5to8.exe.
        /// </summary>
        public static string UmiA_exe {
            get {
                return ResourceManager.GetString("UmiA_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UminekoHane\en\Umineko no Naku Koro ni Hane.exe.
        /// </summary>
        public static string UmiH_exe {
            get {
                return ResourceManager.GetString("UmiH_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umineko1to4\Umineko1to4.exe.
        /// </summary>
        public static string UmiQ_exe {
            get {
                return ResourceManager.GetString("UmiQ_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\notepad.exe.
        /// </summary>
        public static string UmiS_exe {
            get {
                return ResourceManager.GetString("UmiS_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UminekoTsubasa\en\UminekoTsubasa Patch.exe.
        /// </summary>
        public static string UmiT_exe {
            get {
                return ResourceManager.GetString("UmiT_exe", resourceCulture);
            }
        }
    }
}
